PS_PAH = ../

CC = /usr/local/bin/g++-8

#CC = mpicxx
#CFLAGS = -g -ffast-math -funroll-loops -DDEBUG
CFLAGS = -O3
#CFLAGS += -DPARTICLE_SIMULATOR_THREAD_PARALLEL -fopenmp
#CFLAGS += -DSJOGREEN  -DI2000_VARIABLE_SMTH -DENERGY_GUARD

#CFLAGS += -DKI2000_W6_ADIA  -DI2000_VARIABLE_SMTH -DENERGY_GUARD
CFLAGS +=-D KI2000_W6_CHEM  -DI2000_VARIABLE_SMTH -DENERGY_GUARD
#CFLAGS += -DRELAXATION -DI2000_SECOND_ORDER_RIEMMAN_SOLVER -DI2000_VARIABLE_SMTH -DENERGY_GUARD
#CFLAGS += -DBLASTWA/VE -DI2000_SECOND_ORDER_RIEMMAN_SOLVER -DI2000_VARIABLE_SMTH -DENERGY_GUARD
#CFLAGS += -DBLASTWAVE -DI2000_SECOND_ORDER_RIEMMAN_SOLVER -DI2000_VARIABLE_SMTH -DENERGY_GUARD

#CFLAGS += -DBLASTWAVE -DI2000_VARIABLE_SMTH -DENERGY_GUARD
CFLAGS += -DPARTICLE_SIMULATOR_ONE_DIMENSION

CPPOBJS = $(patsubst %.cpp, %.o, $(wildcard *.cpp))
CPPHDRS = $(wildcard *.h)
	
PROGRAM = xgsph.out

.PHONY:	clean all

all:	$(CPPOBJS) $(CPPHDRS) $(FOBJS) $(FHDRS)
	@echo "Linking object files..."
	@$(CC) $(CFLAGS) $(WARNINGS) $(CPPOBJS) -o $(PROGRAM) $(LIBS) $(PS_PATH)
	@echo $(FHDRS)
	@echo [$(CC) $(CFLAGS) $(WARNINGS) $(CPPOBJS) -o $(PROGRAM) $(LIBS) $(PS_PATH)]
	@echo "Link Success! [$(PROGRAM)]"

%.o:	%.cpp $(CPPHDRS)
	@echo "Bulding $< ..."
	@$(CC) -c $< $(CFLAGS) $(WARNINGS) $(PS_PATH)
	@echo "[$< OKssss]"
	
clean:
	-rm *.out *.o